### ISSUE TITLE
bug profiel pagina

### ISSUE THREAD

**Issue by remcodezwart** [Mbozuwa/LetsEvents#195]
Bij de pagina waar ik mijn profiel kan wijzigen
kan ik een ongeldigen email invoeren, ongeldig telefoon nummer

**Comment by BJvAntwerpen** [comment]
Phone number: 0000000000
email: one@home.qwerty

**Comment by Raymond-Wijkhuizen** [comment]
Opgelost op profiel pagina.
Tevens opgelost op de signup pagina
Verie 0.3.6
