### ISSUE TITLE
plaatje profiel

### ISSUE THREAD

**Issue by remcodezwart** [Mbozuwa/LetsEvents#196]
ik krijg geen info over de grooten van het plaatje of bestand, of welke typen bestanden ik kan gebruiken

**Comment by Raymond-Wijkhuizen** [comment]
V0.3.1

**Comment by BJvAntwerpen** [comment]
ik krijg een 'Illuminate \ Http \ Exceptions \ PostTooLargeException' als ik een plaatje wilt gebruiken
hij was maar 23040*12960
ik verwachte dat zo'n error word opgevangen

**Comment by Raymond-Wijkhuizen** [comment]
Error message 413 zal worden toegevoegd
