### ISSUE TITLE
De notificatie bij het inschrijven van een event.

### ISSUE THREAD

**Issue by Ian-Storm** [Mbozuwa/LetsEvents#207]
Als ik mij inschrijf voor een event op de event pagina om niet mee te doen en dan verander naar wel mee doen krijg ik nog steeds een notificatie van dat ik niet mee doe aan dat event. (omgekeerd doet hij hetzelfde)

**Comment by Raymond-Wijkhuizen** [comment]
Fixed in V0.3.5
