### ISSUE TITLE
Slechte installatie stappenplan

### ISSUE THREAD

**Issue by BJvAntwerpen** [Mbozuwa/LetsEvents#222]
Het is een verkeerde werk volgorde.
Eerst een 'composer install' en een 'php artisan migrate:fresh --seed' met de standaard laravel bestanden en daarna de werkbestanden pas toevoegen werkt niet.
De 'migrate' helemaal niet omdat de database connectie info pas stap 7 is en de 'migrate' is stap 5.

Daarnaast kan ik via de localhost url de website wel bereiken maar werkt de website niet goed ("startpagina" gaat naar 'localhost'). Ik moest een virtual host aanmaken.

**Comment by Laussii078** [comment]
New installation document will be written at final release (or earlier if needed).
Solved for now,
