### ISSUE TITLE
Create error

### ISSUE THREAD

**Issue by alexkalis** [Mbozuwa/LetsEvents#283]
Bug Name: 
Create won't work on chrome.

Area Path: 
Create new event
fill in data
push the create button

Build Number: 
Version Number 3.0.8

Severity: HIGH 
Priority: Medium

Reported By: Alex Kalis
Reported On: 21-11-2018

Reason: Defect
Environment: Windows 2003/SQL Server 2005
chrome Version 70.0.3538.110 (Official Build) (64-bit)

Description:
User can not create an event in chrome, because the button gets disabled but the page doesn't go the the store function.

**Comment by Laussii078** [comment]
#300 - Bug fixed.
