### ISSUE TITLE
admin kan gebruikers afbeelding niet aanpassen

### ISSUE THREAD

**Issue by JHJLuijten** [Mbozuwa/LetsEvents#288]
Area Path: 
http://ao-letsevent.local/profile/1

Build Number: 
Version Number 3.0.8

Severity:LOW
Priority: LOW

Reported By: Your Name
Reported On: Date

Reason: missing code

Description:
bug gevonden dat je als admin een gebruiker wilt bewerken (in het admin menu om gebruikers op non actief te zetten) dat die een fout melding geeft en geen bewerk functie

**Comment by Raymond-Wijkhuizen** [comment]
#295 Bug fixed
21-11-2018
