### ISSUE TITLE
QueryException on event delete

### ISSUE THREAD

**Issue by Laussii078** [Mbozuwa/LetsEvents#303]
**Bug Name:** 
QueryException shown when deleting event which has users.

**Area Path:** 
ACCOUNT menu > My events

**Build Number:** 
Version Number 0.3

Severity: Medium
Priority: Medium

Reported By: Laurens
Reported On: 22-11-2018

Reason: Defect
**Environment:** Google Chrome, Windows 8

**Description:**
When deleting an event which already has participants you will get an "Integrity constraint violation" error (QueryException) - _has to do with the foreign key in registration. (Participants should be removed first, when done succesfully and no participants are left the event should be deleted)._

**Comment by alexkalis** [comment]
Can be fixed with a try and catch.

**Comment by Mbozuwa** [comment]
Fixed the issue, it should now correctly display an error when you try to remove an event with participants in it. It also displays a message when you successfully removed an event

Version 0.4.1
