### ISSUE TITLE
test issue + commit

### ISSUE THREAD

**Issue by alexkalis** [Mbozuwa/LetsEvents#378]
Bug Name: 
Application crash on clicking the SAVE button while creating a new user.

Area Path: 
USERS menu > New Users

Build Number: 
Version Number 5.0.1

Severity: HIGH (High/Medium/Low) or 1
Priority: HIGH (High/Medium/Low) or 1

Reported By: Your Name
Reported On: Date

Reason: Defect
Environment: Windows 2003/SQL Server 2005

Description:
Application crash on clicking the SAVE button while creating a new
the user, hence unable to create a new user in the application.

**Comment by Raymond-Wijkhuizen** [comment]
Kan dit gesloten worden?
